from langchain_groq import ChatGroq
from langchain_community.tools.tavily_search import TavilySearchResults

from langgraph.prebuilt import create_react_agent
from langchain_core.messages.ai import AIMessage

from app.config.settings import settings

def get_response_from_ai_agents(llm_id , query , allow_search ,system_prompt):

    llm = ChatGroq(model=llm_id)

    tools = [TavilySearchResults(max_results=2)] if allow_search else []

    agent = create_react_agent(
        model=llm,
        tools=tools,
        state_modifier=system_prompt
    )

    state = {"messages" : query}

    response = agent.invoke(state)

    messages = response.get("messages", [])

    # Filter for AIMessages that have non-empty text content
    ai_contents = [
        message.content for message in messages 
        if isinstance(message, AIMessage) and message.content and isinstance(message.content, str) and message.content.strip()
    ]

    if ai_contents:
        return ai_contents[-1]
    
    # Fallback to the last message content if available
    if messages:
        last_msg = messages[-1]
        return getattr(last_msg, "content", str(last_msg))

    return "No response generated by the agent."






