from langchain_groq import ChatGroq
from langchain_core.tools import tool
from langchain_community.tools.tavily_search import TavilySearchResults
from langgraph.prebuilt import create_react_agent
from langchain_core.messages.ai import AIMessage
from langchain_core.messages import SystemMessage, HumanMessage
from app.config.settings import settings


@tool
def search_web(query: str) -> str:
    """Search the web for up-to-date facts, current news, scores, and real-time events."""
    try:
        tavily = TavilySearchResults(
            max_results=2,
            tavily_api_key=settings.TAVILY_API_KEY
        )
        raw_results = tavily.invoke({"query": query})
        
        if not raw_results:
            return "No relevant web results found."

        # Keep snippets concise to avoid Groq Tokens-Per-Minute (TPM) limits
        cleaned = []
        for item in raw_results:
            content = str(item.get("content", ""))[:350].strip()
            url = item.get("url", "")
            cleaned.append(f"- {content} (Source: {url})")
            
        return "\n".join(cleaned)
    except Exception as e:
        return f"Search service temporarily unavailable: {str(e)}"


def get_response_from_ai_agents(llm_id: str, query, allow_search: bool, system_prompt: str) -> str:
    """
    Invokes the AI agent or direct LLM with optional web search capability.
    Handles query as str or list of strings.
    """
    if isinstance(query, list):
        query_text = " ".join(str(q) for q in query if q).strip()
    else:
        query_text = str(query).strip()

    if not query_text:
        return "Please provide a valid question or prompt."

    try:
        llm = ChatGroq(
            model=llm_id,
            api_key=settings.GROQ_API_KEY,
            temperature=0.7
        )

        # If search is not requested, invoke model directly (fastest & most reliable)
        if not allow_search:
            messages = [
                SystemMessage(content=system_prompt),
                HumanMessage(content=query_text)
            ]
            response = llm.invoke(messages)
            return response.content if isinstance(response.content, str) else str(response.content)

        # If search is enabled, use ReAct agent with token-optimized search tool
        tools = [search_web]
        agent = create_react_agent(
            model=llm,
            tools=tools,
            state_modifier=system_prompt
        )

        state = {"messages": [HumanMessage(content=query_text)]}
        response = agent.invoke(state)

        messages = response.get("messages", [])

        # Filter for AIMessages that have non-empty text content
        ai_contents = [
            message.content for message in messages
            if isinstance(message, AIMessage) and message.content and isinstance(message.content, str) and message.content.strip()
        ]

        if ai_contents:
            return ai_contents[-1]

        if messages:
            last_msg = messages[-1]
            return getattr(last_msg, "content", str(last_msg))

        return "No response generated by the agent."

    except Exception as e:
        err_msg = str(e)
        if "rate_limit_exceeded" in err_msg or "TPM" in err_msg:
            return "⚠️ Groq Token Rate Limit reached. Please wait a few moments or try without web search."
        return f"❌ Agent Error: {err_msg}"
